// Package config models the app->workspace table, persists it, and generates
// the Hyprland snippet (windowrulev2 + exec-once) that does the relaunch.
package config

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type Entry struct {
	Class     string `json:"class"`
	Workspace int    `json:"workspace"`
	Exec      string `json:"exec"`
	Enabled   bool   `json:"enabled"`
	Float     bool   `json:"float,omitempty"`
}

type Config struct {
	StaggerSeconds int     `json:"staggerSeconds"`
	Entries        []Entry `json:"entries"`
}

func configDir() string {
	base := os.Getenv("XDG_CONFIG_HOME")
	if base == "" {
		base = filepath.Join(os.Getenv("HOME"), ".config")
	}
	return filepath.Join(base, "omarchy-relaunch")
}

func DefaultPath() string { return filepath.Join(configDir(), "config.json") }
func SnippetPath() string { return filepath.Join(configDir(), "relaunch.conf") }

func Load() (*Config, error) {
	c := &Config{}
	b, err := os.ReadFile(DefaultPath())
	if os.IsNotExist(err) {
		return c, nil
	}
	if err != nil {
		return nil, err
	}
	if err := json.Unmarshal(b, c); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}
	return c, nil
}

func (c *Config) Save() error {
	p := DefaultPath()
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return err
	}
	b, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		return err
	}
	tmp := p + ".tmp"
	if err := os.WriteFile(tmp, b, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, p)
}

var knownExec = map[string]string{
	"brave-browser":          "brave",
	"Brave-browser":          "brave",
	"google-chrome":          "google-chrome-stable",
	"chromium":               "chromium",
	"firefox":                "firefox",
	"zen":                    "zen-browser",
	"Alacritty":              "alacritty",
	"kitty":                  "kitty",
	"org.wezfurlong.wezterm": "wezterm",
	"foot":                   "foot",
	"code":                   "code",
	"code-oss":               "code",
	"VSCodium":               "codium",
	"codium":                 "codium",
	"org.telegram.desktop":   "telegram-desktop",
	"Slack":                  "slack",
	"discord":                "discord",
	"vesktop":                "vesktop",
	"obsidian":               "obsidian",
	"thunderbird":            "thunderbird",
	"org.gnome.Nautilus":     "nautilus",
	"thunar":                 "thunar",
	"mpv":                    "mpv",
	"Spotify":                "spotify",
	"spotify":                "spotify",
	"herdr":                  "herdr",
}

func GuessExec(class string) string {
	if e, ok := knownExec[class]; ok {
		return e
	}
	return strings.ToLower(class)
}

func (c *Config) enabledSorted() []Entry {
	entries := make([]Entry, 0, len(c.Entries))
	for _, e := range c.Entries {
		if e.Enabled && e.Class != "" && e.Workspace > 0 {
			entries = append(entries, e)
		}
	}
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Workspace != entries[j].Workspace {
			return entries[i].Workspace < entries[j].Workspace
		}
		return entries[i].Class < entries[j].Class
	})
	return entries
}

func (c *Config) Snippet() string {
	entries := c.enabledSorted()
	var b strings.Builder
	b.WriteString("# Generated by omarchy-relaunch. Do not edit by hand.\n")
	b.WriteString("# Regenerate via the bar widget or `relaunch generate`.\n\n")
	b.WriteString("# --- Workspace pinning rules ---\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "windowrulev2 = workspace %d silent, class:^(%s)$\n",
			e.Workspace, regexEscape(e.Class))
		if e.Float {
			fmt.Fprintf(&b, "windowrulev2 = float, class:^(%s)$\n", regexEscape(e.Class))
		}
	}
	b.WriteString("\n# --- Launch at startup ---\n")
	for _, e := range entries {
		ex := e.Exec
		if ex == "" {
			ex = GuessExec(e.Class)
		}
		if c.StaggerSeconds > 0 {
			fmt.Fprintf(&b, "exec-once = sleep %d && %s\n", c.StaggerSeconds, ex)
		} else {
			fmt.Fprintf(&b, "exec-once = %s\n", ex)
		}
	}
	return b.String()
}

func (c *Config) WriteSnippet() error {
	p := SnippetPath()
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return err
	}
	tmp := p + ".tmp"
	if err := os.WriteFile(tmp, []byte(c.Snippet()), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, p)
}

func regexEscape(s string) string {
	r := strings.NewReplacer(
		".", `\.`, "+", `\+`, "*", `\*`, "?", `\?`,
		"(", `\(`, ")", `\)`, "[", `\[`, "]", `\]`,
		"{", `\{`, "}", `\}`, "^", `\^`, "$", `\$`, "|", `\|`,
	)
	return r.Replace(s)
}
